name: Code Quality

on: [push, pull_request]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install black ruff mypy

      - name: Run Black
        run: black .

      - name: Run Ruff
        run: ruff check .

      - name: Run Mypy
        run: mypy --exclude build .